### ISSUE TITLE
[Request] Please Provide Examples

### ISSUE THREAD

**Issue by maxobremer** [TTimeGaming/FoundryVTT-Suite-5E#1]
This module looks interesting but i am having a bit of difficulty actually using it. Is it possible some clear examples are added with screenshots to the wiki for:
- Choosing skill proficiencies
- Grant items with choices

In addition the examples compendium is currently empty maybe if there were some examples there then the learning process of this module could be made easier.

The concept of this module looks very useful but it for me at least doesn't feel very intuitive in actual usage

**Comment by TTimeGaming** [comment]
The Wiki has been updated with some fully explained examples, specifically the two you have noted above. These contain screenshots, full tables breaking down the contents of the Active Effect, as well as a few extra details about the setup.

I will work to fix the Examples compendium, as this is a bug that it is empty. Thanks for highlighting.

Please let me know if there is anything else that can be added to the Wiki to ensure ease of use for the module.

**Comment by TTimeGaming** [comment]
[Version 0.3.4](https://github.com/TTimeGaming/FoundryVTT-Suite-5E/releases/tag/v0.3.4) now contains the same examples in Compendium format. Hopefully this makes it a little easier to understand what is needed to get this working.
